angular.module('library.collections',['library.collections.controllers','ui.router']);
angular.module('library.collections').config(function($stateProvider,$urlRouterProvider,$locationProvider){
        $stateProvider.state('collections.categories',{
                url:'/categories',
                templateUrl:'modules/collections/views/categories.html',
                controller:'categoriesController'
        });
        $stateProvider.state('collections.books',{
                url:'/categories/:id',
                templateUrl:'modules/collections/views/books.html',
                controller:'booksController'
        });
        $stateProvider.state('collections.bookInfo',{
                url:'/categories/:id/:permaLink',
                templateUrl:'modules/collections/views/bookInfo.html',
                controller:'booksInfoController'
        });
        $urlRouterProvider.otherwise('/categories');
        $locationProvider.html5Mode(false);
    
    });